language: python
python:
  - 2.7
  - 3.6
install:
  - sudo apt-get install python3-tk
  - pip install -r requirements.txt
  - python setup.py develop
script:
  - pytest --cov pyitab pyitab
after_success:
  - codecov