name: neuropy
dependencies:
  - python=3.7
  - pip
  - numpy
  - nomkl
  - python-blosc
  - cytoolz
  - scipy=1.2
  - matplotlib
  - cython
  - tk
  - pip:
     - mne
     - jupyter
     - seaborn
     - nibabel
     - nitime
     - imbalanced-learn
     - pandas
     - bokeh
     - dask
     - dask-jobqueue
     - dask-kubernetes
     - distributed
     - joblib
     - nilearn
     - pybids
     - scikit-learn
     - nistats
     - hmmlearn
     - statsmodels
     - h5py
     - pymvpa2
     - pybids
     - pytest
     - mne-hcp
